language: objective-c
cache: cocoapods
xcode_workspace: HackeratiWhiteLabel.xcworkspace
xcode_scheme: HackeratiWhiteLabel
xcode_sdk: iphonesimulator
osx_image: xcode7.3

env:
  - IOS_VER="9.3" FL_ARGS="verify"

before_script:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (${IOS_VER}) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - ./fastlane/travis.sh

after_failure:
  - tail -n 500 ./build/xcodebuild.og